name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t your-frontend-image:latest ./frontend

      - name: Run Tests
        run: |
          docker run your-frontend-image:latest npm test  # Make sure to configure your tests

  deploy:
    name: Deploy Frontend to Vercel
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Vercel
        run: |
          npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod
